spring:
  application:
    name: crud-app
  datasource:
    url: jdbc:postgresql://localhost:5432/crud_database
    username: postgres
    password: Nariman111

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
